io_definitions:
  model_checkpoint: '../../checkpoints/phys_uncoupled/run/checkpoints/R2_E+F+A/'
  model_definition: '../../model_definitions/phys_uncoupled/'
  start_struct: '../../start_structs/bulk.xyz'
  start_index: 0
  #out_path: './output/traj.traj'
  out_path: 'output/traj.traj'
md_definitions:
  timestep: 0.5 # in fs
  steps_per_frame: 1
  temperature: 300
  total_steps: 2_000_000
  field_vector: [0,0,0.]
