# Model configuration
checkpoint_folder: '../training_runs/model_i_alldata/run/checkpoints/R2_E+F+A/'
model_definitions: '../model_i/'

# Data paths
validation_data_path: '/work/pstaerk/datasets_ml/bingqing_finite_apt/valid'
output_path: '/work/pstaerk/outs/physical_i_alldata_bulk/'

# Model parameters
cutoff: 5.0
field: null
predict_i: true

# Batching parameters
num_edges: 150000
num_nodes: 5000
num_graphs: 2
batch_style: 'batch_shape'

# Ewald parameters
lr_wavelength_factor: 8.0
smearing_factor: 4.0

# Other parameters
stress: false
apt: true
prefetch_size: 2
output_screen: false
