chunk_size: 1
loss_weights:
  energy: 1.0
  forces: 1.0
lr_decay:
  start_decay_after: 10
  stop_decay_after: 2000
  style: linear
max_steps: 6006000
min_learning_rate: 1.0e-06
model:
  model.Critias:
    activation: silu
    cutoff: 5.0
    cutoff_fn: cosine_cutoff
    features_efield: 64
    max_degree: 4
    max_degree_sphere: 4
    message_degree: 0
    n_rad_e: 10
    num_radial: 32
    num_scalar: 128
    num_species: 4
    num_spherical: 8
    old_efield: true
    radial_basis: basic_bernstein
    semilocal_radial: false
    semilocal_spherical: false
n_train: 3003
n_valid: 750
num_parameters: 246290
start_learning_rate: 6.0e-05
training_pipeline:
  num_edges: 28000
  num_graphs: 2
  num_nodes: 385
  style: shape
valid_every: 6006
worker_buffer_size: 1
worker_count: 2
