chunk_size: 4
loss_weights:
  apt: 1.0
  energy: 1.0
  forces: 1.0
lr_decay:
  start_decay_after: 10
  stop_decay_after: 2000
  style: linear
max_steps: 2490000
min_learning_rate: 1.0e-06
model:
  model.Critias:
    activation: silu
    cutoff: 5.0
    cutoff_fn: cosine_cutoff
    features_efield: 64
    max_degree: 3
    max_degree_sphere: 4
    message_degree: 0
    n_rad_e: 10
    num_radial: 64
    num_scalar: 16
    num_species: 4
    num_spherical: 10
    old_efield: true
    radial_basis: basic_bernstein
    semilocal_radial: false
    semilocal_spherical: false
n_train: 1245
n_valid: 311
num_parameters: 67360
start_learning_rate: 0.0001
training_pipeline:
  num_edges: 28000
  num_graphs: 2
  num_nodes: 385
  style: shape
valid_every: 2490
wandb_id: tz9mof37
worker_buffer_size: 1
worker_count: 2
