io_definitions:
  model_checkpoint: '../../training_runs/lorem_i_cluster_bulk_td//run/checkpoints/R2_E+F+A/'
  model_definition: '../../lorem_i/'
  start_struct: '../../../datageneration/hexamer_isomers/book.xyz'
  start_index: 0
  out_path: '/work/pstaerk/md_runs_ml/lorem_i_hex_book_com/traj.traj'
md_definitions:
  timestep: 0.5 # in fs
  steps_per_frame: 1
  temperature: 10
  total_steps: 50_000
  field_vector: [0,0,0.]
