io_definitions:
  model_checkpoint: '../../checkpoints/phys_uncoupled/run/checkpoints/R2_E+F+A/'
  model_definition: '../../model_definitions/phys_uncoupled/'
  start_struct: '../../start_structs/cage.xyz'
  start_index: 0
  #out_path: '/work/pstaerk/md_runs_ml/physical_i_hex_cage_com/traj.traj'
  out_path: 'output/traj.traj'
md_definitions:
  timestep: 0.5 # in fs
  steps_per_frame: 1
  temperature: 10
  total_steps: 300_000
  field_vector: [0,0,0.]
