chunk_size: 1
loss_weights:
  apt: 1.0
  energy: 1.0
  forces: 1.0
lr_decay:
  start_decay_after: 10
  stop_decay_after: 2000
  style: linear
max_steps: 6006000
min_learning_rate: 1.0e-06
model:
  lorem.Lorem:
    cutoff: 5.0
    cutoff_fn: cosine_cutoff
    equivariant_message_passing: false
    initialize_node_features: false
    lr: true
    max_degree: 6
    max_degree_lr: 0
    num_features: 128
    num_message_passing: 0
    num_radial: 32
    num_species: 8
    num_spherical_features: 8
    radial_basis: basic_bernstein
n_train: 3003
n_valid: 750
num_parameters: 1052429
start_learning_rate: 6.0e-05
training_pipeline:
  num_edges: 160000
  num_graphs: 2
  num_nodes: 5000
  style: shape
valid_every: 6006
worker_buffer_size: 1
worker_count: 2
