io_definitions:
  model_checkpoint: '../../checkpoints/phys_lr_only/run/checkpoints/R2_E+F/'
  model_definition: '../../model_definitions/phys_lr_only/'
  start_struct: '../../start_structs/book.xyz'
  start_index: 0
  # out_path: './output/traj.traj'
  out_path: 'output/traj.traj'
md_definitions:
  timestep: 0.5 # in fs
  steps_per_frame: 1
  temperature: 10
  total_steps: 50_000
  screen_fac: 
  field_vector: [0,0,0.]
