io_definitions:
  model_checkpoint: '../../checkpoints/lorem_coupl_local/run/checkpoints/R2_E+F+A/'
  model_definition: '../../model_definitions/lorem_coupl_local/'
  start_struct: '../../start_structs/bulk.xyz'
  start_index: 0
  out_path: '/work/pstaerk/md_runs_ml/lorem_ii_bulk_300K_new/traj.traj'
md_definitions:
  timestep: 0.5 # in fs
  steps_per_frame: 1
  temperature: 300
  total_steps: 400_000
  field_vector: [0,0,0.]
